# Generated by Django 3.2.6 on 2021-08-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('kumulatif', models.IntegerField(default=0)),
                ('sembuh', models.IntegerField(default=0)),
                ('dalam_perawatan', models.IntegerField(default=0)),
                ('meninggal', models.IntegerField(default=0)),
            ],
        ),
    ]
