# Generated by Django 3.2.6 on 2021-08-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPerKecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('sagulung', models.IntegerField(default=0)),
                ('bulang', models.IntegerField(default=0)),
                ('batu_aji', models.IntegerField(default=0)),
                ('belakang_padang', models.IntegerField(default=0)),
                ('sekupang', models.IntegerField(default=0)),
                ('lubuk_baja', models.IntegerField(default=0)),
                ('batu_ampar', models.IntegerField(default=0)),
                ('bengkong', models.IntegerField(default=0)),
                ('nongsa', models.IntegerField(default=0)),
                ('batam_kota', models.IntegerField(default=0)),
                ('galang', models.IntegerField(default=0)),
                ('sei_beduk', models.IntegerField(default=0)),
            ],
        ),
    ]
