# Generated by Django 3.2.6 on 2021-08-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dataperkecamatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataharian',
            name='tanggal',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='tanggal',
            field=models.DateField(unique=True),
        ),
    ]
