# Generated by Django 3.2.6 on 2022-01-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210823_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataperkecamatan',
            name='transit',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataharian',
            name='dalam_perawatan',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataharian',
            name='kumulatif',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataharian',
            name='meninggal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataharian',
            name='sembuh',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='batam_kota',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='batu_aji',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='batu_ampar',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='belakang_padang',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='bengkong',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='bulang',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='galang',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='lubuk_baja',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='nongsa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='sagulung',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='sei_beduk',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataperkecamatan',
            name='sekupang',
            field=models.IntegerField(blank=True),
        ),
    ]
